// DATOS DE MATERIAS POR CARRERA - ISER 2026

const CARRERAS = {
  locucion: {
    nombre: "LOCUCION INTEGRAL",
    turnos: ["TM", "TT", "TN"],
    sheets: {
      TM: "1oldn5a_IuUMXfsJy61AC6u4Ri9v2tztr4y0IwE6XYZ0",
      TT: "1hJXQJPUIoVgtKMcq6vM6dzvcAhp5KfeElPNAGVmyn4Y",
      TN: "1L7MJ-VPr49b95C9tRvg9eN4EAlv2Ky0dHSxo2sTm3Mk",
    },
    folders: {
      TM: "1Okms-Ia9ahMAFQX593VM5ijWR-LLJK_j",
      TT: "1ciNrDCW5jnb3y5cc0lBpxaFvhfBnxCz1",
      TN: "1K5pIBB00AI0azr21lqUDQrxThYCG3ZoH",
    },
    anios: 3,
    pendientes: {
      "Primer Año": [
        "Expresión Corporal",
        "Tecnología I",
        "Informática",
        "Exp. Oral y Escrita",
        "Teorías de la Comunicación",
        "Pron. del Francés",
        "Pron. del Alemán",
        "Historia I",
        "Música",
      ],
      "Segundo Año": [
        "Interpretación",
        "Inves y Red Periodística",
        "Literatura",
        "Pron. del Italiano",
        "Publicidad",
        "Tecnología II",
        "Taller de Libretos y Guiones",
        "Historia II",
        "Princ. de Estética e Historia del Arte",
      ],
      "Tercer Año": [
        "Oratoria",
        "Redacción",
        "Inglés",
        "Portugués",
        "Planific. y Gest. de Medios",
        "Régimen Legal",
        "Geopolítica",
        "Ética Profesional",
      ],
    },
    recursar: {
      "Primer Año": [
        "Locución I",
        "Foniatría I",
        "Expresión Corporal",
        "PITV I",
        "PIR I",
        "Tecnología I",
        "Informática I",
        "Exp. Oral y Escrita",
        "Teorías de la Comunicación",
        "Pron. del Francés",
        "Pron. del Alemán",
        "Historia I",
        "Música",
      ],
      "Segundo Año": [
        "Locución II",
        "Foniatría II",
        "Interpretación",
        "PITV II",
        "PIR II",
        "Inves y Red Periodística",
        "Literatura",
        "Pron. del Italiano",
        "Publicidad",
        "Tecnología II",
        "Taller de Libretos y Guiones",
        "Historia II",
        "Princ. de Estética e Historia del Arte",
      ],
      "Tercer Año": [
        "Locución III",
        "Foniatría III",
        "Oratoria",
        "Doblaje",
        "PITV III",
        "PIR III",
        "Redacción",
        "Inglés",
        "Portugués",
        "Planific. y Gest. de Medios",
        "Régimen Legal de la Radiodifusión",
        "Geopolítica",
        "Ética Profesional",
      ],
    },
  },

  produccion: {
    nombre: "PRODUCCION Y DIRECCION DE RADIO Y TV",
    turnos: null,
    sheet: "1fcAlvgtKZkfKr5vcqVuxJp_XbulXGKNXK7nb05IIP44",
    folder: "16ci5U_1DyE9vLjPbxIyBNxVMpZMbcOP3",
    anios: 3,
    pendientes: {
      "Primer Año": [
        "GEI I",
        "Prin. edición y leng audiovisual",
        "Sonido y Musicalización",
        "Fundamentos de Tecnología",
        "Comp. e Iluminación",
        "Géneros Radiales y Televisivos",
        "Metodología Aplicada",
        "Vestuario y Ambientación",
        "Inglés I",
        "Historia del Arte",
      ],
      "Segundo Año": [
        "Post-Producción",
        "GEI II",
        "Puesta en Escena",
        "Realización Publicitaria",
        "TV de Exteriores",
        "Seminario de Creatividad",
        "Taller de Redacción",
        "Inglés II",
        "Historia Americana y Argentina",
        "Historia del Arte Contemporáneo",
        "Literatura I",
      ],
      "Tercer Año": [
        "GEI III",
        "Radio y TV Educativa",
        "Gestión y Adm de Produc",
        "Dirección de Doblaje",
        "Régimen Legal",
        "Sem de Industrias Culturales",
        "Literatura II",
      ],
    },
    recursar: {
      "Primer Año": [
        "GEI I",
        "Prin. edición y leng audiovisual",
        "Sonido y Musicalización",
        "Fundamentos de Tecnología",
        "Comp. e Iluminación",
        "PITV I",
        "PIR I",
        "Géneros Radiales y Televisivos",
        "Metodología Aplicada",
        "Vestuario y Ambientación",
        "Inglés I",
        "Historia del Arte",
      ],
      "Segundo Año": [
        "Post-Producción",
        "GEI II",
        "Puesta en Escena",
        "Realización Publicitaria",
        "TV de Exteriores",
        "PITV II",
        "PIR II",
        "Seminario de Creatividad",
        "Taller de Redacción",
        "Inglés II",
        "Historia Americana y Argentina",
        "Historia del Arte Contemporáneo",
        "Literatura I",
      ],
      "Tercer Año": [
        "GEI III",
        "Radio y TV Educativa",
        "Gestión y Adm de Produc",
        "Dirección de Doblaje",
        "PITV III",
        "PIR III",
        "Régimen Legal",
        "Sem de Industrias Culturales",
        "Literatura",
      ],
    },
  },

  guion: {
    nombre: "GUIONISTA DE RADIO Y TELEVISION",
    turnos: null,
    sheet: "1-gQUz98J6zXMN3hegqcn3OdXKQ9rsWWHJE9yxJosfF8",
    folder: "1pzZnxR1CAcxEhiC0687D2L9fYD0CvcKk",
    anios: 3,
    pendientes: {
      "Primer Año": [
        "Historia del espectáculo",
        "Taller de Escritura",
        "Creatividad I",
        "Inglés I",
        "Teorías de la Comunicación",
        "Informática e Internet",
        "Metodología de la Investigación",
      ],
      "Segundo Año": [
        "Creatividad II",
        "Inglés II",
        "Semiología",
        "Producción Radial y Televisiva",
        "Historia Social Argentina",
      ],
      "Tercer Año": [
        "Creatividad III",
        "Lenguaje de las Artes Plásticas",
        "Lenguaje de la Música",
        "Técnicas de Actuación",
        "Introducción al Conocimiento Cultural",
      ],
    },
    recursar: {
      "Primer Año": [
        "Guión I",
        "Lenguaje Audiovisual I",
        "Literatura Dramática",
        "Taller de Práctica Profesional I",
        "Historia del espectáculo",
        "Taller de Escritura",
        "Creatividad I",
        "Inglés I",
        "Teorías de la Comunicación",
        "Informática e Internet",
        "Metodología de la Investigación",
      ],
      "Segundo Año": [
        "Guión II",
        "Lenguaje Audiovisual II",
        "Géneros Literarios y Audiovisuales",
        "Taller de Práctica Profesional II",
        "Creatividad II",
        "Inglés II",
        "Semiología",
        "Producción Radial y Televisiva",
        "Historia Social Argentina",
      ],
      "Tercer Año": [
        "Guión III",
        "Lenguaje Audiovisual III",
        "Taller de Práctica Profesional III",
        "Creatividad III",
        "Lenguaje de las Artes Plásticas",
        "Lenguaje de la Música",
        "Técnicas de Actuación",
        "Introducción al Conocimiento Cultural",
      ],
    },
  },

  operacion_radio: {
    nombre: "OPERADOR TECNICO - ORIENTACION RADIO",
    turnos: null,
    sheet: "1kERlIgGAzd853vyiAV3kLGxIXJ0e2cACKsZK4RKztcw",
    folder: "1tnU1QgJ0tgy6th-eg6waUmdMIGQepSZM",
    anios: 3,
    pendientes: {
      "Primer Año": [
        "Electroacústica",
        "Inglés técnico I",
        "Introducción a la electrónica",
        "Introducción a las Tecn. digitales",
        "Sistemas operativos de computación",
        "Eq. e Inst. de estudios de radio",
      ],
      "Segundo Año": [
        "Régimen Legal de la Radiodif.",
        "Inglés técnico II",
        "Historia de la cultura",
        "Práctica profesional I",
        "Sistemas digitalización de audio",
      ],
      "Tercer Año": [
        "Semiología",
        "Inglés técnico III",
        "Metodología de la investigación",
        "Nuevas tecnologías de comunicaciones",
        "Práctica profesional II",
      ],
    },
    recursar: {
      "Primer Año": [
        "Electroacústica",
        "Inglés técnico I",
        "Introducción a la electrónica",
        "Introducción a las Tecn. Digitales",
        "Sistemas operativos de computación",
        "Operación estudio radio I",
        "Eq. e Inst. de estudios de radio",
      ],
      "Segundo Año": [
        "Régimen Legal de la Radiodif.",
        "Inglés técnico II",
        "Operación estudio radio II",
        "Historia de la cultura",
        "Práctica profesional I",
        "Sistemas digitalización de audio",
      ],
      "Tercer Año": [
        "Semiología",
        "Inglés técnico III",
        "Metodología de la investigación",
        "Nuevas tecnologías de comunicaciones",
        "Op. de Sist. de audio profesional",
        "Sistema de edición digital",
        "Práctica profesional II",
      ],
    },
  },

  operacion_tv: {
    nombre: "OPERADOR TECNICO - ORIENTACION TELEVISION",
    turnos: null,
    sheet: "1fHlfDWqBHxi6nko3VR-9KZUZIoGILa-nqmQOseVQFpw",
    folder: "1FldpevsgG5ldu6Ail9CeIcmYKZ_5yCLU",
    anios: 3,
    pendientes: {
      "Primer Año": [
        "Electroacústica",
        "Inglés técnico I",
        "Introducción a la electrónica",
        "Introducción a las Tecn. digitales",
        "Sistemas operativos de computación",
        "Composición y fotografía",
        "Eq. e Inst. de estudios de TV",
        "Intro. a las Posproduccion. de video",
      ],
      "Segundo Año": [
        "Régimen Legal de la Radiodif.",
        "Inglés técnico II",
        "Historia de la cultura",
        "GEI",
        "Introducción a la producción TV",
      ],
      "Tercer Año": [
        "Semiología",
        "Inglés técnico III",
        "Metodología de la investigación",
        "Nuevas tecnologías de comunicaciones",
        "Posproducción",
        "GEI 2",
        "Montaje",
      ],
    },
    recursar: {
      "Primer Año": [
        "Electroacústica",
        "Inglés técnico I",
        "Introducción a la electrónica",
        "Introducción a las Tecn. digitales",
        "Sistemas operativos de computación",
        "Operación estudio TV 1",
        "Composición y fotografía",
        "Eq. e Inst. de estudios de TV",
        "Intro. a las Posproduccion. de video",
      ],
      "Segundo Año": [
        "Régimen Legal de la Radiodif.",
        "Inglés técnico II",
        "Audio",
        "Historia de la cultura",
        "Cámara",
        "Iluminación",
        "Posproducción de video",
        "GEI",
        "Introducción a la producción TV",
      ],
      "Tercer Año": [
        "Semiología",
        "Inglés técnico III",
        "Metodología de la investigación",
        "Nuevas tecnologías de comunicaciones",
        "Práctica de posproducción",
        "Posproducción",
        "GEI II",
        "Montaje",
      ],
    },
  },

  operacion_planta: {
    nombre: "OPERADOR TECNICO - ORIENTACION PLANTA TRANSMISORA",
    turnos: null,
    sheet: "1qdz-vK005obrUi9czpOR8-4Ey7wMCFp0gQayuXafxME",
    folder: "1yk7EG39Vrz4fS7yEA5djY-p_cC5KoSRj",
    anios: 2,
    pendientes: {
      "Primer Año": [
        "Electroacústica",
        "Inglés técnico I",
        "Introducción a la electrónica",
        "Introducción a las Tecn. digitales",
        "Sistemas operativos de computación",
        "Electrónica aplicada a planta AM",
        "Suministro de energía",
      ],
      "Segundo Año": [
        "Régimen Legal de la Radiodifusión",
        "Inglés técnico II",
        "Electro. Aplic. A planta FM y TV",
        "Eq. Estudio radio y TV",
        "Mediciones prácticas electrónicas",
        "Tec. Dig. Aplic a planta FM y TV",
      ],
    },
    recursar: {
      "Primer Año": [
        "Electroacústica",
        "Inglés técnico I",
        "Introducción a la electrónica",
        "Introducción a las Tecn. digitales",
        "Sistemas operativos de computación",
        "Tecn. Oper. Y Mant. De planta AM",
        "Electrónica aplicada a planta AM",
        "Suministro de energía",
      ],
      "Segundo Año": [
        "Régimen Legal de la Radiodifusión",
        "Inglés técnico II",
        "Tecn. Oper. Y Mant. De planta CATV",
        "Tecn. Oper. Y Mant. De planta FM",
        "Tecn. Oper. Y Mant. De planta TV",
        "Electro. Aplic. A planta FM y TV",
        "Eq. Estudio radio y TV",
        "Mediciones y prácticas electrónicas",
        "Tec. Dig. Aplic a planta FM y TV",
      ],
    },
  },

  convergencia: {
    nombre: "CONVERGENCIA",
    turnos: null,
    sheet: "19Zs_T4-3RfYfoVIjJ6LJ_Qx0Cu-Lgl0SI_G2X6AwVeg",
    folder: "1JPGgS0e_uyj0xYzdIY1phbhHuNd8UnfL",
    anios: 3,
    pendientes: {
      "Primer Año": [],
      "Segundo Año": [],
      "Tercer Año": [],
    },
    recursar: {
      "Primer Año": [],
      "Segundo Año": [],
      "Tercer Año": [],
    },
  },
};

// Exportar para uso en Node.js (API) y browser
if (typeof module !== "undefined" && module.exports) {
  module.exports = { CARRERAS };
}
